---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example
  labels:
    app: example
spec:
  type: ClusterIP
  selector:
    app: example
  ports:
  - name: example
    port: 8080
    targetPort: example
    protocol: TCP
