---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: example  # deploy to example namespace
  labels:
    app: TODO
    asdf: example

spec:
  type: ClusterIP
  selector:
    app: example
  ports:
  - name: example
    port: 8080  # main service port
    targetPort: example
    protocol: TCP
