---
apiVersion: apps/v1  # first, required
kind: Deployment  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app: TODO  # first, required
  annotations: {}
spec:  # required
  replicas: 1  # first
  revisionHistoryLimit: 10
  selector:  # required
    matchLabels:  # preferred
      app: TODO  # first, required
  strategy:  # preferred
    type: RollingUpdate  # preferred
  template:  # required
    metadata:  # required
      labels:  # required
        app: TODO  # first, required
    spec: {}  # required, ditto=Pod.spec
